### ISSUE TITLE
UFS compilation error: gettid not found

### ISSUE THREAD

**Issue by SpiderMonkey1975** [ufs-community/ufs-weather-model#109]
Hi,

I am trying to build UFS with CCPP disabled.  I keep getting the following compilation error:

[ 17%] Building Fortran object FV3/gfsphysics/CMakeFiles/gfsphysics.dir/physics/sfcsub.F.o
/ufs-weather-model/FMS/affinity/affinity.c:31:14: error: static declaration of 'gettid' follows non-static declaration
   31 | static pid_t gettid(void)
      |              ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from /ufs-weather-model/FMS/affinity/affinity.c:24:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;

I am compiling on a Ubuntu 19.10 Linux laptop using MPICH 3.1.4 for MPI support.  Any assistance would be appreciated!

**Comment by climbfuji** [comment]
What version of the GNU compiler are you using?

Note that the error is not from the file you listed in the build log. You are seeing this because you are building with multiple threads. The error comes from building FMS. I don't recall the details, but there have been issues with the affinity code on some systems in the past.

How do you build the model? Using `compile.sh` or `compile_cmake.sh`?

**Comment by DusanJovic-NOAA** [comment]
See https://github.com/NOAA-GFDL/FMS/issues/276

I assume you are talking about the develop branch. In the public release branch we removed ``affinity.c`` from the list of files we compile due to this issue. 

https://github.com/ufs-community/ufs-weather-model/commit/4a1e67e86a7c316425b39a4c5668c5cc4ed110c7

One of many changes we need to cherry pick from ``release/public-v1``

**Comment by climbfuji** [comment]
> See [NOAA-GFDL/FMS#276](https://github.com/NOAA-GFDL/FMS/issues/276)
> 
> I assume you are talking about the develop branch. In the public release branch we removed `affinity.c` from the list of files we compile due to this issue.
> 
> [4a1e67e](https://github.com/ufs-community/ufs-weather-model/commit/4a1e67e86a7c316425b39a4c5668c5cc4ed110c7)
> 
> One of many changes we need to cherry pick from `release/public-v1`

Speaking of which, when do we want to do this? The earlier the better in my opinion.

**Comment by DusanJovic-NOAA** [comment]
I agree. See https://github.com/ufs-community/ufs-weather-model/issues/69
Many of the changes can be combined with some other PRs, since they do not change baselines.

**Comment by junwang-noaa** [comment]
In the code commit google sheet, it's after  Celluar Automata commit, so it
will be in the week 5/11, but I think it may come in early.

**Comment by edwardhartnett** [comment]
I am seeing this problem with current develop branch. It is expected to be resolved?

The FMS package has a functioning build system based on autotools. Why not use it?

**Comment by DusanJovic-NOAA** [comment]
Is this still an issue?

**Comment by junwang-noaa** [comment]
Since we haven't heard from issue creator for 3 weeks, we will close the issue. Please let us know if user wants to reopen it.
