### ISSUE TITLE
 Using FMS 2021.04 in ufs-weather-model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1105]
## Description
FMS 2022.01 is coming soon. It contains the updates including an option to ignore checksums. Ufs-weather-model will be updated to use FMS 2022.01.

20220321 Update: GFDL found  potential performance regression for GFDL models with FMS 2022.01. We will update FMS to 2021.04 in ufs-weather-model.

## Solution
When FMS 2022.01 is released, the fms lib will be added on all the ufs-weather-model supported platforms and tested in ufs-weather-model. A PR will be made to ufs-weather-model to use the new version.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, since fms/2022.01 is still not released yet, maybe we can just switch to use fms/2021.04 at this moment, which is sufficient for the moving-nesting capability. BTW, the fms/2021.04 version has already been installed under hpc-stack on all ufs-weather-model supported platforms. See https://github.com/NOAA-EMC/hpc-stack/issues/395.

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA updated. @DusanJovic-NOAA would you please test FMS 2021.04 in ufs-weather-model? Thanks

**Comment by junwang-noaa** [comment]
@kgerheiser @Hang-Lei-NOAA I want to confirm with you, the fms 2021.04 was installed with avx, right?

**Comment by Hang-Lei-NOAA** [comment]
yes
