### ISSUE TITLE
compiler/library updates Q4FY2022

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#1323]
This EPIC includes compiler and library updates.

1) FMS 2022.03 with mixed mode capability
2) FMS 2022.05 transition to fms2_io
3) ESMF 8.3.0 release.
4) MAPL/Yafyaml updates
5) w3nco 2.4.1 -> w3emc 2.9.2

**Comment by DeniseWorthen** [comment]
NCEPlibs needs to install these updates and then they need to be included in UFS.

**Comment by DeniseWorthen** [comment]
This will be a EPIC task in the future on all RDHPCS machines; EIB will take care of only WCOSS2. 

Dusan has opened PR for ESMF library to hpc-stack (spack-stack). EPIC is working on getting spack-stack working. 

Many small fixes in ESMF update; main fix is attribute type for history (8.3.1 , patch of 8.3.0). 

ESMF updated PIO in 8.3.0; binary format was removed and stricter usage of attribute type-kind caused problem. Caused issues for downstream users/tools.

AQM cap will need update to remove ESMF binary output format to use 8.3.1. 

8.4.0beta11 also has same fixes; could update to that. 

Do we want to stick to public release version (8.3.1) or snapshot (8.4.0.beta11)? Frequency of ESMF releases set to 6months. Release candidate (3-4 wks prior to release) would be good to have tested.

Spack-stack may make this more possible (testing release candidates)?

**Comment by DeniseWorthen** [comment]
Ufuk reports that 8.4 should be released soon; first week of November 2022 is planned at this point (8.4.0beta20).

AQM will not use older ESMF since it needs to use release version (8.3.1 or 8.4) for implementation. Brian will followup w/ AQM cap updates. 

Jun clarifies that issue for updates needs to be created on hpc-stack; EPIC installs on RDHPCS. EMC takes care of acorn/wcoss2; submit new library request to NCO every 2months; may take 2 months to install. Need different strategy for wcoss2 testing.

LiPan reports 8.4 does not work with MAPL, due to PIO issue. PIO on acorn needs update to later version. LiPan will followup w/ information about PIO.

**Comment by DeniseWorthen** [comment]
Use of Gaea-C5 may work as a standin for wcoss2 since they have same architecture once it is available.

**Comment by DeniseWorthen** [comment]
ESMF can be updated directly to 8.4.0 release (skipping 8.3.1 patch). External PIO option will be used. Hang Lei reports that he believe that the release version of ESMF 8.4 will resolve the issue w/ MAPL but it needs to be tested.

**Comment by junwang-noaa** [comment]
I am closing this issue, separate issues have been created from fms 2023.01 and esmf 840 installation.
