### ISSUE TITLE
Update PIO to version 2.5.7 on WCOSS2

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#1348]
## Description
WCOSS2 is currently using pio 2.5.2 but 2.5.3 is required for UFSWM.

Once 2.5.3 is installed we need to bump the version in modulefiles/ufs_wcoss2.intel and modulefiles/ufs_wcoss2.intel_debug

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Just want to confirm, the PIO is approved on wcoss2 and GRIT will install 2.5.3 or do we still need to make request to install pio/2.5.3 on wcoss2?

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa I talked with Hang earlier and he said he completed the code delivery to NCO this morning for 2.5.3.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Is this an item that depends on the 2-month install cycle on WCOSS2?

**Comment by Hang-Lei-NOAA** [comment]
The PIO/2.5.3 was delivered to NCO on July/28 before the agreement with
NCO.
The PIO delivered to NCO in this time is PIO/2.5.7.
https://docs.google.com/spreadsheets/d/1iEYR_Z6vomZDKLfYB6bBz4lAHafnU8EpUUsO3zUjs7c/edit#gid=0

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA , good to know. We should test with it, to see if it changes baselines. Does this version exist on RDHPCS machines (if you're aware of it?)

**Comment by Hang-Lei-NOAA** [comment]
Yes, UFS people asked me to install PIO2.5.7 one month ago. Because the
latest ESMF8.4.0 only works with pio/2.5.7 and later.

**Comment by BrianCurtis-NOAA** [comment]
I'm testing 2.5.7 on WCOSS2 right now.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Lets get PIO 2.5.7 tested on an RDHPCS machine so we can get a PR in for PIO 2.5.7.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 RT's pass with PIO 2.5.7

**Comment by Hang-Lei-NOAA** [comment]
Hi, All

NCO put the pio/2.5.3 on acorn now. Please test it and let me know the
result. Then NCO will move it to dogwoods and cactus.

PIO is now ready for testing on acorn.  To refresh your memory (it has been
a while since we discussed this), it is a little tricky as it is being
built with the newest version of hdf5 (1.12.0 - a version where the known
bug has been fixed) and the newest version of netcdf to differentiate from
the 4.7.4 version built against the older version of hdf5(1.10.x). Judging
from the Unidata site, there could be runtime errors trying to run the old
netcdf with the new hdf5 though I have not confirmed this.  We had talked
about adding additional hierarchy elements to lmod to include hdf5 and
netcdf - and I am still on board with doing it that way - but for now the
new modules are just at the intel...cray-mpich level for testing.  Acorn's
lmod seems a little broken at this point with some other libraries missing,
I will look into that when I get back from vacation (I'll mostly be out
next week).

Acorn currently has the new craype loaded but testing of pio using the
prior one is possible as follows.

module purge
module load envvar
module load intel/19.1.3.304
module load craype/2.7.13
module load cray-mpich/8.1.12

module load hdf5/1.12.0

module load netcdf/4.9.0

module load pio 2.5.3

You can put whomever will be testing this directly in touch with me.
If there are any questions feel free to contact me and I will do what
I can to help with the testing.

Cheers,

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 has PIO 2.5.7 here:
```
---- /apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7 ----
   esmf/8.2.1b04 (D)    ncdiag/1.0.0           pio/2.5.7    (L,D)
   esmf/8.3.0b09 (L)    ncio/1.0.0             upp/10.0.8
   fms/2021.03          ncio/1.1.2      (D)    w3emc/2.7.3
   fms/2021.04          nemsio/2.5.2    (D)    wrf_io/1.2.0 (D)
   fms/2022.01   (L)    nemsiogfs/2.5.3 (D)
   fms/2022.02   (D)    pio/2.5.2
```
Now we need to wait on RDHPCS machines to install 2.5.7

**Comment by BrianCurtis-NOAA** [comment]
This made it into the dust scheme pr

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun

I sent the request this morning. PIO was approved. v2.5.2 was installed.

Thanks,
Hang
