### ISSUE TITLE
Wave model cannot restart if mediator flag is set to startup

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-weather-model#1546]
## Description
Full description is in https://github.com/NOAA-EMC/WW3/issues/870

### To Reproduce:
set KEEP to true in rt.sh
Run the cpld_control_p8 and cpld_restart_p8 tests.
In the cpld_restart_p8 directory change
start_type = continue to
start_type = initial
and model will have an error with a time mismatch.

## Additional context
- needed for Ensemble Prototype 4 experiments.

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

**Comment by DeniseWorthen** [comment]
@pjpegion I am not able to reproduce this error. 

This is how I tested it, using the current develop branch of UWM. 

1) I ran the RTs for ``cpld_control_noaero_p8`` and ``cpld_control_nowave_noaero_p8`` . 
2) I used the ``cpld_control_noaero_p8`` to create a run directory for a warmstart test with waves.
3) I copied the ``cpld_control_nowave_noaero_p8`` FV3 and MOM6 restarts at hour=18 to ``warmstart/INPUT`` and the CICE6 hour=18 restart to ``warmstart``, replacing the ``cice_model.res.nc`` file. 
4) I made the following namelist changes
-  I changed the input.nml to have the typical restart values (warm_start = .true., nggps_ic = .false. etc) 
- I changed the start_hour to 18 in model_configure
- I changed use_restart_time to .true. in ice_in
5) I used an nml file for WW3 instead of the inp file. This allows me to skip changing all the dates in the ww3_shel.in file. But I repeated my test using the shel.inp file and got the same results.

My run directory is ``/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_8484``

**Comment by pjpegion** [comment]
@DeniseWorthen which coupled restart file did you use (ufs.cpld.cpl.r.....nc) ?

**Comment by pjpegion** [comment]
I just checked your warmstart directory, and in model_configure fhrot = 0.  The issue with the wave model is when fhrot is != 0

**Comment by DeniseWorthen** [comment]
@pjpegion I'm assuming that what you are doing is using "native" restarts as ICs for a model run. So, for example instead of using a CICE6 IC derived from CFSR, you use an actual CICE6 restart from an earlier run. Same for FV3 and MOM6. The restarts are used as ICs for a true warmstart, but it is not a restart run. That is the nature of a "startup" run. It requires setting fhrot=0. For a "startup" run, there is no reading of the mediator restart file.

**Comment by pjpegion** [comment]
What need to run long forecasts at the end of the IAU cycle, which has the model starting with fhrot=3.  In our case we did not run replay with waves, but EMC needs to run the long forecasts with waves.
 In any case it seems to me that the wave model should initialize with the current time, not the forecast start time

**Comment by DeniseWorthen** [comment]
The startTime and currTime are set in the Driver and depend on fhrot. 

If start_type=startup, then runtype=initial, fhrot=0 and currTime=startTime. 
If start_type=continue, then runtype=continue, fhrot>0 and currTime is startTime + fhrot

**Comment by pjpegion** [comment]
But what about the case when start_type=startup and fhrot=3?  That is what will be needed to initialize with the replay initial conditions.   The mediator does not have the wave fields in the restart, and we need have a startTime at 00z so the forecast hours are correct.

**Comment by junwang-noaa** [comment]
@pjpegion If I understand correctly, you are trying to restart the model with a different configuration. The restart files were created from atm-ocn-ice configuration, but you want to restart the model with atm-ocn-ice-wav without wave related restart fields, is it correct? I'd suggest creating a different branch to handle this specific case because we actually want to prevent this configuration from running in operation. E.g. if one component failed to create restart files, then the model should throw error message, instead of allow restart to run from the available restart files. Just my own opinion.

**Comment by pjpegion** [comment]
@junwang-noaa,  what I am proposing here would still fail in the situation you describe.  In order to run without one of the restart files, you have to change the nems.configure file to start_type=initial.  
It is also my opinion that this model should support different ways to initialize the model, not just what will go into operations,  the goal is to have the UFS be both a research and operational model.

**Comment by DeniseWorthen** [comment]
@pjpegion @junwang-noaa In nems.configure, the start_type must be "startup" (which then sets the component runtype to initial) if you're not starting with the same component mix. If you attempt to use ``start_type=continue``, then the run will fail because CMEPS cannot find the fields for the added component in the mediator restart file. The model at this point just crashes; I can make a small fix in CMEPS which provides an error message instead.

In WW3, I have an alternate fix to the one proposed by Phil which retains the same inital/continue logic but makes use of the time offset (as is done for fhrot in the UFSDriver). The change is 

```
    call ESMF_ClockGet( clock, startTime=startTime, currTime=currTime, rc=rc)
    timeoffset = currTime - startTime

    ! Initial run or restart run
    if ( runtype == "initial") then
      call ESMF_ClockGet( clock, startTime=esmfTime, rc=rc)
      if (ChkErr(rc,__LINE__,u_FILE_u)) return
#ifndef CESMCOUPLED
      esmfTime = esmfTime + timeoffset
#endif
    else
      call ESMF_ClockGet( clock, currTime=esmfTime, rc=rc )
      if (ChkErr(rc,__LINE__,u_FILE_u)) return
    endif
```

This is also B4B with all current coupled tests. 

The actual issue that I found with the original code is that WW3 will hang because the loop over timesteps gets set up as ``do it = 1,-59``. I see how that is happening, but I don't understand the startup logic that WW3 is using to get there.

I've also built a new test which will run the ``cpld_control_noaero_p8`` test as a dependent warm start test from ``cpld_control_nowave_noaero_p8``. In this case,  FV3, MOM6 and CICE6 use the restart files, but WW3 starts cold and ``start_type=startup``. I guess you could say CMEPS also starts cold in this case. All the other settings (including fhrot>0) are the typical warm start settings. Would we want to add this use-case as a new RT test?

**Comment by junwang-noaa** [comment]
To be honest, I am not sure if we want to set up some mismatched cold/warm start case. If I understand correctly, in this case, FV3, MOM6, and CICE are warm started, while ww3 and CMEPS are cold started. We are running a full (real) restart cases in operation. What will happen to a real restart test when WW3 restart files are missing? Will WW3 code report error for such case or it will allow model to continue to run? Do we need additional code to accommodate both situations? Also how many developers need to run this mismatched cold/warm start cases?

**Comment by JessicaMeixner-NOAA** [comment]
I think this is a current GEFS development need, specifically for @pjpegion, Bing Fu and myself and likely others.

**Comment by DeniseWorthen** [comment]
In a true restart case, start_type will be continue. For most components, if the restart file does not exist then the run would fail. I do think WW3 is an exception in this case because it seems there is a default start-up option (ie, it can always start cold). 

This fix wouldn't change that situation because in that case, start_type would be continue. Nothing is changing for the continue case. I do think there probably needs a fix made to prevent WW3 from cold-starting if it is really meant to be using a restart file (which for some reason was not written). 

I did wonder if we needed a new start_type (CESM uses the name "hybrid") but for them the existing code works because of how they set the run up at the script level. So this seemed like the cleanest option to provide the use-case, which as Jessica mentions is apparently needed.

**Comment by junwang-noaa** [comment]
@pjpegion I thought you are going to rerun GEFS analysis with wave, can you confirm that we still need this feature in UFS?

**Comment by pjpegion** [comment]
@junwang-noaa the production of the GEFSv13 initial conditions will be with waves, but this feature will be needed in other configurations.
