### ISSUE TITLE
missing files in s3 bucket

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1569]
## Description
The input-data-20221101/FV3_fix_tiled folder is missing in S3 bucket (noaa-ufs-regtests-pds). I could able to download those file before (input-data-20220414). I think I did not catch this error before since I am using GitHub cache to get the input files rather than downloading them again and again. The solution would be put that folder again to S3 bucket since GitHub Action depend on it if the cache is removed (if you don't access it in 7 days, GitHub automatically deletes it).

### To Reproduce:
Try to download the tiled fix files from S3 bucket.

## Additional context
N/A

## Output
N/A

**output logs**
My GitHub Action is giving following error,

```
downloading files using s3 protocol ...
[1750](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1780)
end_point = noaa-ufs-regtests-pds and file = input-data-20221101/FV3_fix_tiled/C96/C96.maximum_snow_albedo.tile1.nc
[1751](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1781)
Traceback (most recent call last):
[1752](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1782)
  File "/home/runner/work/_actions/uturuncoglu/nuopc-comp-testing/main/scripts/get_input.py", line 125, in s3_get
[1753](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1783)
    md5sum_remote = s3.head_object(Bucket=end_point, Key=f)['ETag'][1:-1]
[1754](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1784)
  File "/home/runner/.local/botocore/client.py", line 530, in _api_call
[1755](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1785)
    return self._make_api_call(operation_name, kwargs)
[1756](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1786)
  File "/home/runner/.local/botocore/client.py", line 960, in _make_api_call
[1757](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1787)
    raise error_class(parsed_response, operation_name)
[1758](https://github.com/esmf-org/noahmp/actions/runs/3943134405/jobs/6747823097#step:2:1788)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

**Comment by uturuncoglu** [comment]
I also check the bucket from command line as following and the folder is not there.

` aws s3 ls --no-sign-request s3://noaa-ufs-regtests-pds/input-data-20221101/FV3_input_data/`

**Comment by ShawnCebulaNOAA** [comment]
@jkbk2004 this sounds like it may be more in Code Management's field than User Support.  I'll keep an eye on this thread to make sure there's something going on and get a hold of the team other ways if necessary @uturuncoglu 

Shawn Cebula - EPIC End User Support

**Comment by uturuncoglu** [comment]
@jkbk2004 Is it possible to copy the missing directory to S3 easily?

**Comment by ulmononian** [comment]
@uturuncoglu have you tried to retrieve the files you need recently? it looks like some of them are timestamped early on 1/18/23 for some reason.

i was able to retrieve input-data-20221101/FV3_fix_tiled/C96/C96.maximum_snow_albedo.tile1.nc (the file listed in your github actions error log) using a different protocol on jet, namely: "wget -q -c -T 30 -t 3 https://noaa-ufs-regtests-pds.s3.amazonaws.com/input-data-20221101/FV3_fix_tiled/C96/C96.maximum_snow_albedo.tile1.nc". 

it looks like /input-data-20221101/FV3_input_data/ exists here: https://noaa-ufs-regtests-pds.s3.amazonaws.com/index.html#input-data-20221101/FV3_input_data and input-data-20221101/FV3_fix_tiled is here: https://noaa-ufs-regtests-pds.s3.amazonaws.com/index.html#input-data-20221101/FV3_fix_tiled/.

maybe give it another try? if it doesn't work, perhaps something funny is going on with the gh actions interface w/ s3.

**Comment by CSyl** [comment]
@ulmononian & @uturuncoglu Please keep in mind the data will get updated for every new update made to the datasets against the UFS-WM's develop branch. Also, to maintain the latest 2months of dataset updates, there is a set schedule to only the latest 2months of dataset updates made to code. Please check the bucket again because the data for FV3_fixed tiled is present. See below:
https://noaa-ufs-regtests-pds.s3.amazonaws.com/index.html#input-data-20221101/FV3_fix_tiled/

**Comment by uturuncoglu** [comment]
@CSyl @ulmononian Thanks for your help. I could download now. Did you push anything new to the bucket? I am asking because I could not find that particular directory before. Anyway, I think it won't be a problem of changing `input-data-20221101` directory if it changes since it is managed by a simple YAML file. The only think that if the action tries to find the files and could not find then it will fail.

**Comment by CSyl** [comment]
@uturuncoglu  Yeah, np. The most recently merged sets of datasets (input, develop, BMIC, WW3) have been  migrated to cloud. Those datasets would be:

**DEVELOP DATA: ['20230112']
'INPUTDATA_ROOT': ['20221101']
'INPUTDATA_ROOT_WW3': ['20220624']
'INPUTDATA_ROOT_BMIC': ['20220207']**

Per, the latest commit merged https://github.com/ufs-community/ufs-weather-model/commit/e051e0eac36171127f10422a5b447b517dcb30b6.

Keep in mind that because the migration of data to cloud does depend on an RDHPCS as its data source and maintenance issues on the RDHPCS file system occurs (which it did yesterday), then there will be an interruption in data migration and as a result, the migration to cloud was re-executed early this morning.  Should you find a directory missing at the time you check the cloud it could be because either of an RDHPCS ongoing maintenance by IT or it is in the midst of migrating the newly set of datasets that were just merged to the UFS-WM develop branch.
 
   Also, the way these objects are setup in cloud is with their key set as the file directory as seen on the on-premise RDHPCS -- in effort to preserve their as seen on-premise data structure.

**Comment by junwang-noaa** [comment]
@uturuncoglu Can we close the issue? Thanks

**Comment by uturuncoglu** [comment]
@junwang-noaa yes, we could close this for now. I was able to get those missing files. If I have any issue I could open another issue for it. Thanks.
