### ISSUE TITLE
Model builds fail on NOAA Cloud systems

### ISSUE THREAD

**Issue by natalie-perlin** [ufs-community/ufs-weather-model#2092]
## Description
UFS-WM builds fail on NOAA Cloud systems (ParallelWorks)

### To Reproduce:
Check out model code on NOAA Azure, NOAA AWS, or NOAA GCloud. 
The code would not build. 

## Output
As reported by @kbooker79 :

**Screenshots**
![Screenshot 2024-01-10 at 4 30 45 PM](https://github.com/ufs-community/ufs-weather-model/assets/68030316/cafda4b1-d75d-4be0-9050-c1748319c538)

**output logs**
If applicable, include relevant output logs.

**Comment by ulmononian** [comment]
tests on aws using 1.5.1 (compile and run for both control_c48 and cpld_control_p8) are successful. 

still looking into this on azure. gcp is not currently available.

there is a proposed upgrade to spack-stack/1.5.1 for ufs_noaacloud.intel in https://github.com/ufs-community/ufs-weather-model/pull/2115 (this would get noaacloud consistent with all other machines).

**Comment by zach1221** [comment]
> tests on aws using 1.5.1 (compile and run for both control_c48 and cpld_control_p8) are successful.
> 
> still looking into this on azure. gcp is not currently available.
> 
> there is a proposed upgrade to spack-stack/1.5.1 for ufs_noaacloud.intel in #2115 (this would get noaacloud consistent with all other machines).

@ulmononian GCP is working now. Both control_p8 and cpld_control_p8 ran successfully for me. Azure on the other hand will build but the tests are failing.

**Comment by zach1221** [comment]
@ulmononian I got azure to pass cpld_control_p8, control_p8 and some other tests, by running against the weather model executable in the experiment directory that is generated from ./rt.sh, since the compile portion is successful. Then you just need to cd to the experiment directory, load the modules manually, then submit the srun to batch (example): srun --mpi=pmi2 -n number_of_cores /lustre/stmp2/FV3_RT/rt_12345/cpld_control_p8/fv3.exe
