### ISSUE TITLE
Ensure restart-at-end functionality is working in CMEPS

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#2236]
## Description
This UFS WM issue is related to CMEPS issue https://github.com/NOAA-EMC/CMEPS/issues/118.
It will allow UFS WM to write out CMEPS restart files at the end of whole integration.

**Comment by dpsarmie** [comment]
First suggestion was to test the functionality and see where it is work correctly/incorrectly:

This has been tested and atmwav_control_noaero_p8 is able to produce restarts at the end of the run. Further tests with datm_cdeps_control_gefs show that mom and cice is not producing end of run restart files.

Denise suggested looking into if the alarm is being set correctly for mom and cice and I'll be starting there.

**Comment by DeniseWorthen** [comment]
@dpsarmie I thought the mediator was producing the restart file in the datm test, for example DATM_GEFS_*.r.2011-10-02-10800.nc, which is an 24 + 3 hours restart but that mom and cice were not?

**Comment by dpsarmie** [comment]
@DeniseWorthen, yes that's the case. I'll edit my previous comment.

These are the restart files produced for the test with output every 12h and an additional restart at 27h (the end of the run).
![image](https://github.com/ufs-community/ufs-weather-model/assets/42810219/4b06f2c3-9a40-439a-9153-c70a6a9af84f)

**Comment by dpsarmie** [comment]
I've added PRs for the MOM and CICE fixes to the end of run restart issue. During testing I came across a functionality issue that may or may not need to be resolved.

In ufs.configure.datm_cdeps.IN, the configuration option **_restart_option_** does not supersede the end of run restart. (i.e. if **_restart_option_** is set to _None_ or _Never_, an end of run restart file will still be created if _**write_restart_at_endofrun**_ was set to _True_.)

Should the code be changed to have **_restart_option_** control all restarts or keep _**restart_option**_ as it currently is and only control the restart files that are written at a preset interval?

**Comment by DeniseWorthen** [comment]
@dpsarmie What component are you suggesting a code change may need to be made in? We  have no use case for the restart options none or never, but CESM might, so we'd need to be careful about making a change that might impact them.

**Comment by dpsarmie** [comment]
@DeniseWorthen
If we wanted restart_option = None to supersede the write_restart_at_endofrun option, then I would add a NUOPC attribute check in CMEPS, MOM, and CICE to make sure that restart_option is not set to none/never before doing the subsequent checks for the end of run restart.

But I can also see how restart_option is only for the interval restarts (since the other options are nhours/nminutes/etc.) and the argument can be made that restart_option should only control those interval restart files and write_restart_at_endofrun should be where the user should control the end of run restart files.
