### ISSUE TITLE
Enable flexible writing of restart file output time in UFS coupled configuration 

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#2348]
## Description

In the UFS coupled configuration, all the model components write out restart files with restart frequency, but in slightly different ways. It would be good to have a consistent way to enable the model components to write out restart files at flexible output time.

**Comment by dpsarmie** [comment]
The FV3_cap uses a -1 to specify an output forecast hour instead of an output frequency ([fv3 code](https://github.com/NOAA-EMC/fv3atm/blob/develop/module_fcst_grid_comp.F90#L766-805)). 

The option in the other submodules (using a -1 to designate this option) will be used to try and keep things consistent across all submodules.

**Comment by NickSzapiro-NOAA** [comment]
This branch (https://github.com/NickSzapiro-NOAA/ufs-weather-model/tree/restart_fh) is a work in progress to enable forecast hour defined restarts ("restart_fh") in the "same way" as comma-delimited integers in UFS configure component attributes. Code as [Denise implemented in MOM6](https://github.com/ufs-community/ufs-weather-model/pull/2099) lets CMEPS, CICE, FV3 components have option of forecast hour restarts in addition to existing functionality so that can now write at specified frequency and forecast hour, if desired.

These components require more work:
- WW3: Maybe adapt User_restalarm as in ESCOMP/WW3 https://github.com/ESCOMP/WW3/blob/dev/unified/model/src/wav_comp_nuopc.F90
- AQM: I see code deeper at CMAQ level to restart at end of run here: https://github.com/USEPA/CMAQ/blob/2c3338dee0c4fb21692976e4bd6d1892dc22016d/CCTM/src/driver/driver.F#L870-L881

I understand that requested hours not on the interval of the relevant timestep(s) should be skipped. TODO is to log valid and skipped forecast hour restarts from UFS configure restart_fh input

**Comment by junwang-noaa** [comment]
PR #2419 is merged. Close issue
