### ISSUE TITLE
Port ufs-weather-model to acorn (WCOSS2 TDS)

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [ufs-community/ufs-weather-model#292]
## Description
We got access to acorn, a WCOSS2 TDS (Test Development System). UFS must be ported to WCOSS2.

## Solution
Add support to the build system and regression test to build and run tests on WCOSS2.

See PR #291

**Comment by DusanJovic-NOAA** [comment]
Debug version of ESMF library is not (yet) available, so `modulefiles/wcoss2/fv3` and `modulefiles/wcoss2/fv3_debug` are identical.

**Comment by DusanJovic-NOAA** [comment]
`fv3_ccpp_wrtGauss_netcdf_parallel` test crashed on acorn with this error.
```
 in fcst run phase 2, na=           0
 in fcst run phase 2, na=           1
 line          391 NetCDF: HDF error
MPICH ERROR [Rank 148] [job id 83a195bd-3b1e-454a-9447-cc19004723da] [Fri Nov 20 18:12:19 2020] [unknown] [nid001005] - Abort(1) (rank 148 in comm 496): application called MPI_Abort(comm=0x84000001, 1) - process 148

aborting job:
application called MPI_Abort(comm=0x84000001, 1) - process 148
```
Looks like NetCDF/HDF library error.

**Comment by edwardhartnett** [comment]
What version of HDF5 and netCDF were used for this?

**Comment by DusanJovic-NOAA** [comment]
hdf5/1.10.6
netcdf/4.7.4

**Comment by edwardhartnett** [comment]
Were the netCDF parallel I/O tests run when it was built?

**Comment by edwardhartnett** [comment]
Also what is line 391 from? Feel free to provide additional info. ;-)

**Comment by DusanJovic-NOAA** [comment]
I believe that line is from netcdf library. I see it here:
`libdispatch/derror.c:    return "NetCDF: HDF error";
`
But I do not know where line number 391 comes from.

**Comment by edwardhartnett** [comment]
Was this built with hpc-stack?

This is a bit like 20 questions. ;-) 

Can you please take the time to write up a proper issue, with all the relevant information? Please answer my questions about whether the netCDF tests were run.

If you believe that you have found a netCDF bug, we need a small program that does not depend on any other code (except netcdf), which demonstrates the problem. That is always going to be the first step in demonstrating that you have found an actual netCDF bug, and not just a bug in your netCDF code. ;-)

Once you have such a test program, you're going to need to post it as an issue in either netcdf-c or netcdf-fortran, and mention me in the issue so I can try to fix it.

This issue does not contain nearly enough information to debug an actual netCDF problem. You will have to provide more compete information if you believe you have found a netCDF bug.

**Comment by DusanJovic-NOAA** [comment]
> Were the netCDF parallel I/O tests run when it was built?

I don't know. The hpc-stack was built by the NCEPLIBS group. @Hang-Lei-NOAA do you know if parallel I/O tests were run on wcoss2.

**Comment by Hang-Lei-NOAA** [comment]
Yes, the  parallel IO tests  run

**Comment by edwardhartnett** [comment]
I need to see the full output of configure and make check, including the config.log file.

I don't actually have access to this system yet, the paperwork is still working its way through...

**Comment by DusanJovic-NOAA** [comment]
@Hang-Lei-NOAA Can you provide netcdf log files from hpc-stack installation on acorn. Thanks.

**Comment by Hang-Lei-NOAA** [comment]
This option is default in hpc-stack netcdf.
Due to the system fix,  since yesterday, /lfs/h2/ is not
available/accessible til now,  but I have a backup in /lfs/h1.
Please see the content from the log file
=====
+ ../configure
--prefix=/lfs/h2/emc/nceplibs/noscrub/hpc-stack/test/noaa/intel/
19.1.1.217/cray-mpich/8.0.15/netcdf/4.7.4 --enable-cdf5 --disable-dap
--enable-netcdf-4 --enable-parallel4 --disable-doxygen
--enable-parallel-tests
configure: netCDF 4.7.4
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
configure: checking user options
checking whether a NCIO_MINBLOCKSIZE was specified... 256
checking for valgrind... no
checking if fsync support is enabled... no
checking if jna bug workaround is enabled... no
checking whether we should build netCDF-4... yes
checking whether we should build with HDF5... yes
checking do we require hdf5 dynamic-loading support... yes
checking whether reading of HDF4 SD files is to be enabled... no
checking whether to fetch some sample HDF4 files from Unidata ftp site to
test HDF4 reading (requires wget)... no
checking whether we should attempt to install netcdf-fortran
(EXPERIMENTAL)... no
*checking whether parallel IO tests should be run... yes*
checking whether a user specified program to run mpi programs... mpiexec
checking whether a default chunk size in bytes was specified... 4194304
checking whether a maximum per-variable cache size for HDF5 was
specified... 67108864
checking whether a number of chunks for the default per-variable cache was
specified... 10
checking whether a default file cache size for HDF5 was specified...
16777216
checking whether a default file cache maximum number of elements for HDF5
was specified... 4133
checking whether a default cache preemption for HDF5 was specified... 0.75
c

**Comment by climbfuji** [comment]
Stupid question, because I was running into a similar problem on gaea with those two tests failing when creating a new baseline:
```
fv3_ccpp_wrtGauss_netcdf_parallel
fv3_ccpp_regional_quilt_netcdf_parallel
```
Did you enable on the PARALLEL_NETCDF build in the ufs-weather-model cmake config? For gaea, I added
```
set(PARALLEL_NETCDF ON  CACHE BOOL "Enable parallel NetCDF" FORCE)
```
to `cmake/configure_gaea.intel.cmake`. Now trying again if those tests pass or not.

**Comment by climbfuji** [comment]
> Stupid question, because I was running into a similar problem on gaea with those two tests failing when creating a new baseline:
> 
> ```
> fv3_ccpp_wrtGauss_netcdf_parallel
> fv3_ccpp_regional_quilt_netcdf_parallel
> ```
> 
> Did you enable on the PARALLEL_NETCDF build in the ufs-weather-model cmake config? For gaea, I added
> 
> ```
> set(PARALLEL_NETCDF ON  CACHE BOOL "Enable parallel NetCDF" FORCE)
> ```
> 
> to `cmake/configure_gaea.intel.cmake`. Now trying again if those tests pass or not.

Update - in my case, these two tests now pass.

**Comment by DusanJovic-NOAA** [comment]
Done in #295
