### ISSUE TITLE
production/GFSv16: check all compile option failed for GFSv16 atmospere model

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#455]
## Description
NCO requires to test "-check all" option with GFSv16 optimization mode (FFLAGS_OPT). GDAS ENKF, GADS forecast, GFS forecast Model failed with the executable built with the "-check all" option. 

### To Reproduce:

Checked out the GFS.v16.0.15 tag and add "-check all,noarg_temp_created" in FFLAGS_OPT compile options, then run GFS parallel test on wcoss, the run will fail with error message: 
"forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable DTDT_M when it is not allocated
ERR=152"

bugzilla ticket is [#1204](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1204).

Fixes will be made to production/GFSv16 branch for future GFS minor upgrades.

**Comment by junwang-noaa** [comment]
When compiling with "-check all,noarg_temp_created,nopointer", the GFS forecast can run until the wall clock is reached.

**Comment by climbfuji** [comment]
This dtdt_m issue was raised more than a year ago in the NOAA-EMC GFDL_atmos_cubed_sphere fork: https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/issues/29

I closed the issue after removing the IPD code, because the CCPP code doesn't have the problem, and since issues generally related to dev/emc on that fork. But GFSv16 is using IPD, which still has the issue.

I also discussed this with @bensonr last week.

**Comment by junwang-noaa** [comment]
@bensonr <https://github.com/bensonr>  We may still need to allocate the
dtdt_m without the if  statement of "if ( idiag%id_mdt > 0 .and.
(.not.do_adiabatic_init) ) then" (line #384 in
FV3/atmos_cubed_sphere/model/fv_dynamics.F90),  if there is no other
simpler way to fix the error.

**Comment by junwang-noaa** [comment]
The code changes (-check all,noarg_temp_created,nopointer)  was committed to production branch, close this issue.
