### ISSUE TITLE
Update Guide to UFS weather model

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-weather-model#464]
## Description

The UFS weather model guide is out of scope

## Solution
Add a clear and concise description of what you want to happen.

The UFS weather model guide under READTHEDOCS needs to be updated to include an overview that represents its current state -- 

      -- atmosphere model
      -- ocean model
      -- ice model
      -- wave model

## Alternatives

N/A

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:

N/A

**Comment by DeniseWorthen** [comment]
I've made a start on adding the Input/Outputs for the coupled model. I finally was able to build my branch on RTD. I ended up having to add a ``.readthedocs.yml`` file to the root directory otherwise I kept getting build errors about ``sphinxcontrib-bibtex``. 

This is what I have currently on my RTD project page: [rtd](https://ufs-wm-doc-dw.readthedocs.io/en/feature-doc_updates/index.html)
