### ISSUE TITLE
regional_quilt post files show run-to-run variability

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#504]
## Description

During the commit of PR #475, the GRB files for regional_quilt failed to reproduce. 

### To Reproduce:

Create a baseline for the reqional_quilt test using the hash corresponding to PR #475. Attempt to verify the test against that new baseline.

## Additional context

Verification of baselines failed for either the NATLEV.GrbF00 and NATLEV.GrbF24 or the PRSLEV.GrbF00 and PRSLEV.GrbF24.
Additional information can be found in the comment thread [here](https://github.com/ufs-community/ufs-weather-model/pull/475#issuecomment-812054909)

**Comment by junwang-noaa** [comment]
I looked at the code. Two issues have been identified. 
1) some post integer variables have been assigned with large real number. This is fixed by setting those number to 0 as POST code does.

```
% git diff post_regional.F90
@@ -1372,7 +1387,7 @@ module post_regional
                   else
                     islope(i,j) = 0
                   endif
-                  if (abs(arrayr42d(i,j)-fillValue) < small) islope(i,j) = spval
+                  if (abs(arrayr42d(i,j)-fillValue) < small) islope(i,j) = 0
                 enddo
               enddo
             endif

@@ -1925,7 +1940,7 @@ module post_regional
                 do i=ista, iend
                   if (arrayr42d(i,j) < spval) then
                     ivgtyp(i,j) = nint(arrayr42d(i,j))
-                    if( abs(arrayr42d(i,j)-fillValue) < small)  ivgtyp(i,j) = spval
+                    if( abs(arrayr42d(i,j)-fillValue) < small)  ivgtyp(i,j) = 0
                   else
                     ivgtyp(i,j) = 0
                   endif
@@ -1940,7 +1955,7 @@ module post_regional
                 do i=ista, iend
                   if (arrayr42d(i,j) < spval) then
                     isltyp(i,j) = nint(arrayr42d(i,j))
-                    if( abs(arrayr42d(i,j)-fillValue) < small)  isltyp(i,j) = spval
+                    if( abs(arrayr42d(i,j)-fillValue) < small)  isltyp(i,j) = 0
                   else
                     isltyp(i,j) = 0
                   endif
```
2) Post does not initialize all the allocated fields. Some post fields are not available from model history output, nor they are computed in POST, but those fields can still be requested from post control files. Those fields requested from LAM post control file are: averaged surface pressure, averaged/inst 10 m temp, averaged mass exchange coeff, averaged heat exchange coeff. Since they are not available in model history file nor computed in the post code; and they are not initialized, their value can change. It can be fixed by 1) remove those fields in post available field list. 2) remove those fields from post control file so they are not requested. or 3) initialize those fields in post interface to get rid of the run to run differences as we saw in the PR#475.

The code changes for 3) are in post_regional.F90. With the code updates, the post files NATLEV and PRSLEV are identical to the current baseline /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20210330/INTEL/fv3_regional_quilt. 

```
@@ -477,7 +477,7 @@ module post_regional
                              up_heli_max03,up_heli_min03,rel_vort_max01,       &
                              rel_vort_max, rel_vort_maxhy1, refd_max,          &
                              refdm10c_max, u10max, v10max, wspd10max, sfcuxi,  &
-                             sfcvxi
+                             sfcvxi, t10m, t10avg, psfcavg, akhsavg, akmsavg
       use soil,        only: sldpth, sh2o, smc, stc
       use masks,       only: lmv, lmh, htm, vtm, gdlat, gdlon, dx, dy, hbm2, sm, sice
       use ctlblk_mod,  only: im, jm, lm, lp1, jsta, jend, jsta_2l, jend_2u, jsta_m,jend_m, &
@@ -829,6 +829,21 @@ module post_regional
         enddo
       enddo
 !
+!** initialize t10m, t10avg, psfcavg, akhsavg, akmsavg
+!$omp parallel do default(none),private(i,j),shared(jsta_2l,jend_2u,im,spval), &
+!$omp& shared(t10m,t10avg,psfcavg,akhsavg, akmsavg)
+      do j=jsta_2l,jend_2u
+        do i=1,im
+          t10m(i,j) = 0.
+          t10avg(i,j) = 0.
+          psfcavg(i,j) = 0.
+          psfcavg(i,j) = 0.
+          akhsavg(i,j) = 0.
+          akmsavg(i,j) = 0.
+        enddo
+      enddo
+
```

Following fields have value zero, now have a different value.
1272:36122404:vt=2018101500:10 m above ground::TMP Temperature [K]:
    ndata=53261:undef=1891:mean=-1.47574e+20:min=-1.47574e+20:max=-1.47574e+20
    grid_template=1:winds(N/S):
        rotated lat-lon grid:(241 x 221) units 1e-06 input WE:SN output WE:SN res 48
        lat -22.000000 to 22.000000 by 0.200000
        lon 336.000000 to 24.000000 by 0.200000 #points=53261
        south pole lat=-55.500000 lon=262.500000 angle of rot=0.000000

1291:36855780:vt=2018101500:10 m above ground:anl:TMP Temperature [K]:
    ndata=53261:undef=1762:mean=-3.68935e+19:min=-3.68935e+19:max=-3.68935e+19
    grid_template=1:winds(N/S):
        rotated lat-lon grid:(241 x 221) units 1e-06 input WE:SN output WE:SN res 48
        lat -22.000000 to 22.000000 by 0.200000
        lon 336.000000 to 24.000000 by 0.200000 #points=53261
        south pole lat=-55.500000 lon=262.500000 angle of rot=0.000000  

1340:37915657:vt=2018101500:surface::AKHS Surface exchange coefficients for T and Q divided by delta z [m/s]:
    ndata=53261:undef=1879:mean=5.82578e+17:min=-1.48e+20:max=5.9e+20
    grid_template=1:winds(N/S):
        rotated lat-lon grid:(241 x 221) units 1e-06 input WE:SN output WE:SN res 48
        lat -22.000000 to 22.000000 by 0.200000
        lon 336.000000 to 24.000000 by 0.200000 #points=53261
        south pole lat=-55.500000 lon=262.500000 angle of rot=0.000000

1341:37926554:vt=2018101500:surface::AKMS Surface exchange coefficients for U and V divided by delta z [m/s]:
    ndata=53261:undef=1698:mean=1.64804e+18:min=0:max=5.9e+20
    grid_template=1:winds(N/S):
        rotated lat-lon grid:(241 x 221) units 1e-06 input WE:SN output WE:SN res 48
        lat -22.000000 to 22.000000 by 0.200000
        lon 336.000000 to 24.000000 by 0.200000 #points=53261
        south pole lat=-55.500000 lon=262.500000 angle of rot=0.000000

3) It is found that the averaged AHKS/AHMS are computed twice in post code SURFCE.F90. A post issue[#288](https://github.com/NOAA-EMC/EMC_post/issues/288) is created at post repo.
