### ISSUE TITLE
rt.sh: switch to role account on Cheyenne 

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#604]
## Description
Now that we have a role account on Cheyenne, we should switch the `rt.sh` defaults and the auto-rt scripts to use this account.

## Solution
Update `rt.sh` and auto-rt scripts.

## Alternatives
Keep messing around with different users owning regression test baseline directories.

**Comment by BrianCurtis-NOAA** [comment]
right now it seems the REGRESSION_TEST_<compiler> goes to /glade/work/<username>/FV3_RT do we keep that consistent (/glade/work/dtcufsrt/) or switch it to /glade/scratch/dtcufsrt

**Comment by llpcarson** [comment]
What changes would be needed in rt.sh?  The baselines can stay in /glade/p/ral/jntp - with the role-user as owner, I think?

**Comment by BrianCurtis-NOAA** [comment]
somehow my cheyenne autort changes for the switch to $dprefix on ptmp and stmp didn't make it into the repo, but things still worked, so that means i had it locally and never committed it to my repo. That has since been updated and fixed and autort will use the new group account now. rt.sh doesn't need ot be changed as far as I can tell.

**Comment by DeniseWorthen** [comment]
@climbfuji I believe we can close this? I created auto-baselines on Cheyenne on for PR #610. The baseline directory appears w/ dtcufsrt as the owner.

**Comment by climbfuji** [comment]
Yes, this all looks good. Thanks for making the changes.
