### ISSUE TITLE
Some different MPI layouts in regional does not reproduce results

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#649]
## Description
When used to test different MPI decomposition (like layout 3x2 and 2x3) results are bit identical. Now with layout 10x6, we are getting different results if we use 6x10 or any other layout.

### To Reproduce:
This is in all machines/compilers.

## Output

```
paste the code here (if a short section of log)
```

**Comment by climbfuji** [comment]
I was expecting that. We will need the changes from release/public-v2, or better the alternative solution that Lucas described PLUS one change from the release/public-v2 branch.

**Comment by arunchawla-NOAA** [comment]
@RatkoVasic-NOAA is this still an issue with the UFS weather model in regional configurations ?

**Comment by RatkoVasic-NOAA** [comment]
This issue is conditionally solved.
We can reproduce results if we compile model in REPRO mode (-O0 optimization). Unfortunately, if we use operational model, which is compiled with more aggressive optimization, then we are not able to do that.
This issue was recently brought up by HAFS group as well.

**Comment by climbfuji** [comment]
REPRO mode is `-O2` like PROD, but without AVX2, and with `-fp-model strict` instead of `-fp-model source`. DEBUG mode is `-O0`.

**Comment by RatkoVasic-NOAA** [comment]
Dom, thanks for clarification!

**Comment by arunchawla-NOAA** [comment]
I believe GFDL guarantees different layout reproducibility only in repro mode. I will confirm

**Comment by BinLiu-NOAA** [comment]
Hi @RatkoVasic-NOAA, @arunchawla-NOAA, @climbfuji, 

Recently @JunghoonShin-NOAA from the HAFS side did some tests for the regional configuration with different PE layouts. And in his latest tests, even with the REPRO mode, he was not able to get bitwise reproducible results. I believe JungHoon's test was using the [suite_FV3_HAFS_v0_gfdlmp_tedmf.xml](https://github.com/NOAA-EMC/fv3atm/blob/47d391c09a9b7a8c6fe5fff76c61921487891785/ccpp/suites/suite_FV3_HAFS_v0_gfdlmp_tedmf.xml), which is very similar to the [suite_FV3_GFS_v16.xml](https://github.com/NOAA-EMC/fv3atm/blob/47d391c09a9b7a8c6fe5fff76c61921487891785/ccpp/suites/suite_FV3_GFS_v16.xml). 

@RatkoVasic-NOAA, did you test this reproducibility from the RRFS side recently? It might be beneficial to test/confirm the RRFFS can still at least reproduce with different PE layouts in the REPRO mode with its own CCPP suite, with the latest ufs-weather-model develop branch.

Thanks!

**Comment by RatkoVasic-NOAA** [comment]
@BinLiu-NOAA I haven't tested lately. I'm going to do it.

**Comment by JunghoonShin-NOAA** [comment]
Hello all,
I am working in HAFS team with [Bin](https://github.com/BinLiu-NOAA) and would like to provide some updates about reproducibility tests with different PE layouts. Between Feb and March, I conducted the reproducibility tests (on Orion) with different PE layouts, and I tested a) global nesting, b) regional nesting, and c) regional standalone domain configurations.

As Bin mentioned about two weeks ago, when I tried the reproducibility tests with the REPRO mode, I was unable to reproduce the result of regional nesting and regional standalone domain configurations (only reproduced global nesting configuration).
 
So as a final try, I re-ran the reproducibility tests with the dycore_only mode (i.e., without physics) and the REPRO mode. For this test, I set "dycore_only = .true." in the namelist and ran the experiment for the regional nesting and regional standalone domain configurations. But I still failed to reproduce identical results when I used different PE layouts.

Hope this helps to improve the model.
Thank you.

P.S: Below is the summary of my reproducibility tests with different PE layouts
1st reproducibility test (Ran with physics & without REPRO mode): All global nesting, regional nesting, and regional standalone domain configurations didn’t reproduce results.
2nd reproducibility test (Ran with physics & with REPRO mode): Only global nesting configuration reproduced the results, and regional nesting and regional standalone domain configurations didn’t reproduce results.
3rd reproducibility test (Ran without physics & with REPRO mode): Both regional nesting, and regional standalone domain configurations didn’t reproduce the results. Regional standalone domain configuration test crashed after 3-h forecast lead time, but when I checked the results at 3-h forecast lead time, the results were not identical. Global nesting configuration was not tested in this 3rd reproducibility test because it reproduced the result in the 2nd reproducibility test.

**Comment by RatkoVasic-NOAA** [comment]
Thanks @JunghoonShin-NOAA for your input. I'm currently testing reproducibility on hi resolution small domain, regional standalone. Soon, I'll share my results as well.

**Comment by arunchawla-NOAA** [comment]
Thanks guys. I am also flagging @junwang-noaa @rmontuoro and @JessicaMeixner-NOAA . They have been looking at this in the global coupled case as well and seem to have nailed compiler settings. Please see this issue https://github.com/ufs-community/ufs-weather-model/issues/1103 all the way to the end

**Comment by arunchawla-NOAA** [comment]
Hello there is a discussion happening in #1103 that indicates that replacing -fp-model flag from consistent to source leads to reproducible results. Can you test that for your cases to confirm ? For the failures you are having in repro mode

**Comment by climbfuji** [comment]
> Hello there is a discussion happening in #1103 that indicates that replacing -fp-model flag from consistent to source leads to reproducible results. Can you test that for your cases to confirm ? For the failures you are having in repro mode

If so, then this doesn't make sense. `-fp-model consistent` is a stricter standard, forcing the Intel compiler to produce as much as possible consistent math results. It's one step below `-fp-model strict`. `-fp-model source` is less restrictive (and a bit faster). But anyway, if it works it works, it just doesn't make sense to me.

**Comment by arunchawla-NOAA** [comment]
I am opening a discussion topic on this

**Comment by RatkoVasic-NOAA** [comment]
I'm now testing it

**Comment by JessicaMeixner-NOAA** [comment]
@RatkoVasic-NOAA I found I needed to make this fix to run with repro: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/commit/4912bc3cb7bc27f8410413f1e209f10ee198df4d just in case you run into the same error (still testing to see if that works but should?)

**Comment by RatkoVasic-NOAA** [comment]
Mine is already:

set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -O2 -debug minimal -fp-model consistent -qoverride-limits")

just tested with

set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -O2 -debug minimal -fp-model source -qoverride-limits")

and same thing - model not reproduce with different layout.

**Comment by RatkoVasic-NOAA** [comment]
Please see the table:
https://docs.google.com/spreadsheets/d/1RUK063Ml3ES2-wXhk-WymJpf4K1soLmOSpmf7NvTjr8/edit?usp=sharing

Included 25 runs. 
Variable: 
1) dyn-only, dyn+physics
2) PROD vs. REPRO (+ one change in REPRO compilation)
3) different blocksize (15, 16, 32)
4) different MPI layouts (11x10, 10x11, 5x22)

**Comment by kgerheiser** [comment]
I would try with `-fp-model consistent -fp-model precise`. `precise` is implied when using `source`.

**Comment by arunchawla-NOAA** [comment]
what is the physics package here Ratko ?

**Comment by RatkoVasic-NOAA** [comment]
> what is the physics package here Ratko ?

FV3_GFS_v15_thompson_mynn_lam3km (and FV3_GFS_v15_thompson_mynn)

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA can you run the dycore+physics test with DEBUG mode to see if there is any issue with the physics package?

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA can you run the dycore+physics test with DEBUG mode to see if there is any issue with the physics package?

@junwang-noaa I tested DEBUG mode. I got same results as before, different layout did not reproduce:
https://docs.google.com/spreadsheets/d/1RUK063Ml3ES2-wXhk-WymJpf4K1soLmOSpmf7NvTjr8/edit?usp=sharing

**Comment by RatkoVasic-NOAA** [comment]
![image](https://user-images.githubusercontent.com/37597874/159848943-ffa11d7e-48a8-4d50-8a57-528b303d27e1.png)

This is surface temperature difference (*1000) in 00hours. It is possible something in initialization is wrong.
I'll get back to test different physics package (and lower resolution).

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA This does look to me there is some issue with the code. It needs some debug, maybe pick a point and see how the tmpsfc value becomes different with the decompositions.

**Comment by RatkoVasic-NOAA** [comment]
Also tried other physics package, replaced FV3_GFS_v15_thompson_mynn_lam3km with FV3_GFS_v15_thompson_mynn.
Still same results:
https://docs.google.com/spreadsheets/d/1RUK063Ml3ES2-wXhk-WymJpf4K1soLmOSpmf7NvTjr8/edit?usp=sharing

**Comment by RatkoVasic-NOAA** [comment]
Follow-up:
I tested **low resolution** cases and it passed **all tests with REPRO** and with PROD it failed on one case of different blocksize. Low resolution test didn't catch the problem!?

Rows 38-47:
https://docs.google.com/spreadsheets/d/1RUK063Ml3ES2-wXhk-WymJpf4K1soLmOSpmf7NvTjr8/edit?usp=sharing

**Comment by arunchawla-NOAA** [comment]
@RatkoVasic-NOAA based on some of the other conversations, does this problem go away when blending is set to zero ?

**Comment by RatkoVasic-NOAA** [comment]
Yes, but we have to test couple of more cases.

**Comment by RatkoVasic-NOAA** [comment]
> 

@arunchawla-NOAA I'm confirming that without blending boundaries (nrows_blend=0) different MPI decomposition reproduces results.

**Comment by arunchawla-NOAA** [comment]
thanks, so blending is the problem not the different physics packages

**Comment by RatkoVasic-NOAA** [comment]
Correct!

**Comment by junwang-noaa** [comment]
@lharris4 @RatkoVasic-NOAA @MicroTed @bensonr @XiaqiongZhou-NOAA Here is the current status on debugging the regional decomposition reproducibility with blending. @jkbk2004 FYI,

Following @lharris4's suggestion, I am able to run the model and output restart files for one time step. All the tests run with nrows_blend=10 and dycore only without threading. 
- With k_split=1, n_split=1, the decompositions 10x11, 16x6 and 8x12 are reproducing (domain size: 320x192, blocksize=32).  
- The same with  k_split=2, n_split=1. 
- With k_splot=1 and n_split=2,  the two decompositions do not reproduce. The differences show up at the boundary frame (i=1:40, 280:320 and j=1:50, 150:192). 

With k_split=1, n_split=2, I am using two decompositions 16x6 (subdomain size 20x32) and 8x12 (subdomain size 40x16) for debugging. I added some prints in the dycore code. So far the first differences show up in D grid v wind at the decomposition 8x12 PET 0 halo region (i=4, j=17, the point is still in computational domain for 16x6 layout PET 0) after halo update during the second n_split loop (it= 2). The differences then come in field vt then omeg at north boundary at (4,16) inside the computational domains for both decompositions. 

The code is in dyn_core.F90: 
```
     if(mpp_pe()==0) print *,'in dycore, laststep v=',  &
      v(3,17,24:25), v(6,17,24:25),v(4,17,24:25),v(5,17,24:25)

                                                     call timing_on('COMM_TOTAL')
     call complete_group_halo_update(i_pack(8), domain)
      if(mpp_pe()==0) print*,'in dy_core, aft halo_update8, v=',v(3,17,24:25),&
        v(6,17,24:25),v(4,17,24:25),v(5,17,24:25)
```
The results from the two runs are still the same before complete_group_halo_update call, but become different after the call when it=2 (the second time in n_split loop)
It's still not clear to me the blending comes into play at this time. Since the complete_group_halo_update subroutine is actually in FMS which is now a library in UFS and it is not easy to add prints for debugging. I am going to check the PE 8 which has computational domain covering j=17. Meanwhile, if you have any suggestions, please let me know. Thanks

**Comment by RatkoVasic-NOAA** [comment]
@junwang-noaa did you make any changes in the code other than k_split & n_split in namelist?

**Comment by junwang-noaa** [comment]
No, I am using Ted's dycore branch regional_bc_test and did no make any changes except the print lines

**Comment by junwang-noaa** [comment]
Here is some updates. I output the v wind at (4,17) on PET8 (a point inside its computation domain) and compared the value with that in PET0 when it=2(second time in the n_split loop). The are the same before the line:
```
call complete_group_halo_update(i_pack(8), domain)
```
After the call, the PET0 has different value for v wind at (3:6,17) compared to that on PET8 at (3:6,17).  The v wind at (3:6,17) for PET0 in the decomposition 16x6 is consistent with the value on PET8 with decomposition 8x12 before and after the call. I think that makes sense as point (3:6,17) are inside computational domain for both PETs and will not be impacted by the halo update. 

PET0 with decomposition 16x6 for point 
 0:  in dycore, bf halo_update8, v=  -10.26656      -10.77857      -10.67451
 0:   -10.73145      -10.40493      -10.75312      -10.53681      -10.73014     omga
 0:  =  0.0000000E+00  0.0000000E+00 it=           2
 0:  in dy_core, aft halo_update8, v=  -10.26656      -10.77857      -10.67451
 0:   -10.73145      -10.40493      -10.75312      -10.53681      -10.73014

PET8 with decomposition 8x12:
 8:  in dycore, bf halo_update8,pe8 v=  -10.26656      -10.77857      -10.67451
 8:   -10.73145      -10.40493      -10.75312      -10.53681      -10.73014     omga
 8:  =  0.0000000E+00  0.0000000E+00 it=           2
 8:  in dycore, aft halo_update8,pe8 v=  -10.26656      -10.77857      -10.67451
 8:   -10.73145      -10.40493      -10.75312      -10.53681      -10.73014

PET0 with decomposition 8x12:
 0:  in dycore, bf halo_update8, v=  -10.26656      -10.77857      -10.67451
 0:   -10.73145      -10.40493      -10.75312      -10.53681      -10.73014     omga
 0:  =  0.0000000E+00  0.0000000E+00 it=           2
 0:  in dy_core, aft halo_update8, v=  -10.27081      -10.77449      -10.68264
 0:   -10.73160      -10.40990      -10.74941      -10.54211      -10.72647

So it looks to me the blending is causing the complete_group_halo_update not functioning correctly.

**Comment by junwang-noaa** [comment]
The regional_3km and regional_3km_wofs decomposition issue with blending is resolved. An [PR](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/194) was submitted to dycore repo.

**Comment by arunchawla-NOAA** [comment]
Thank you for solving this !

**Comment by climbfuji** [comment]
Yes, that’s correct. It works for some configurations (e.g. global) and/or some physics suites, but it’s not guaranteed.
